with t as (select id from public.legal_topics where name = 'tenancy'),
 d as (
  insert into public.documents (topic_id, title, source_name, source_url, content)
  select t.id, x.title, x.source_name, x.source_url, x.content from t, (values
    ('Landlord and Tenant (Shops, Hotels and Catering Establishments) Act, Cap 301',
     'Kenya Law, Cap 301', 'https://www.kenyalaw.org',
     'Controlled tenancy protections for business premises.'),
    ('Rent Restriction Act, Cap 296',
     'Kenya Law, Cap 296', 'https://www.kenyalaw.org',
     'Protections for residential tenants in controlled premises.'),
    ('Distress for Rent Act, Cap 293',
     'Kenya Law, Cap 293', 'https://www.kenyalaw.org',
     'Rules on how a landlord may lawfully levy distress for unpaid rent.'),
    ('Constitution of Kenya 2010 — housing, property and fair administrative action',
     'Constitution of Kenya 2010', 'https://www.kenyalaw.org',
     'Constitutional rights engaged by evictions and housing disputes.')
  ) as x(title, source_name, source_url, content)
  returning id, title
)
insert into public.chunks (document_id, content, chunk_index)
select d.id, c.content, c.idx from d join (values
 ('Landlord and Tenant (Shops, Hotels and Catering Establishments) Act, Cap 301', 0,
  'Cap 301, s.2(1): a "controlled tenancy" is a tenancy of a shop, hotel or catering establishment which has not been reduced into writing, or which is for a period not exceeding five years, or which contains a provision for termination otherwise than for breach within five years.'),
 ('Landlord and Tenant (Shops, Hotels and Catering Establishments) Act, Cap 301', 1,
  'Cap 301, s.4(2): a landlord who wishes to terminate a controlled tenancy, or to change its terms (including raising rent), must give the tenant a notice in the prescribed Form A of not less than two months before the date the change is to take effect.'),
 ('Landlord and Tenant (Shops, Hotels and Catering Establishments) Act, Cap 301', 2,
  'Cap 301, s.4(4)-(5): the tenant may, within one month of receiving the notice, notify the landlord that they do not agree. The proposed termination or rent change then does not take effect unless the Business Premises Rent Tribunal approves it.'),
 ('Landlord and Tenant (Shops, Hotels and Catering Establishments) Act, Cap 301', 3,
  'Cap 301, s.12: the Business Premises Rent Tribunal may determine or vary rent, order reinstatement of a tenant, award compensation for unlawful eviction, and investigate any complaint relating to a controlled tenancy.'),
 ('Rent Restriction Act, Cap 296', 0,
  'Cap 296, s.4: the Rent Restriction Tribunal has jurisdiction over residential premises whose standard rent does not exceed the prescribed limit, and may assess standard rent, apportion rent, and hear tenant complaints.'),
 ('Rent Restriction Act, Cap 296', 1,
  'Cap 296, s.5: it is an offence for a landlord of controlled residential premises to demand or receive rent in excess of the standard rent assessed by the Tribunal. Excess rent is recoverable by the tenant.'),
 ('Rent Restriction Act, Cap 296', 2,
  'Cap 296, s.6: a landlord may not require a tenant to pay a premium, key money, or an advance of more than two months rent as a condition of granting or renewing a tenancy of controlled premises.'),
 ('Rent Restriction Act, Cap 296', 3,
  'Cap 296, s.15: no order for recovery of possession of controlled residential premises shall be made except on the grounds listed in the Act (such as rent arrears, breach of tenancy, nuisance, or the landlord reasonably requiring the premises), and only where the Tribunal considers it reasonable.'),
 ('Rent Restriction Act, Cap 296', 4,
  'Cap 296, s.16: a landlord who harasses a tenant, or withdraws or withholds services such as water or electricity in order to force the tenant to leave, commits an offence and is liable to a fine or imprisonment.'),
 ('Distress for Rent Act, Cap 293', 0,
  'Cap 293, s.3: distress for rent may only be levied by a landlord or by a certified bailiff licensed under the Act. A landlord who uses uncertified persons to seize a tenant''s goods acts unlawfully.'),
 ('Distress for Rent Act, Cap 293', 1,
  'Cap 293, s.5-6: distress may only be levied for rent actually in arrears, between sunrise and sunset, and may not be levied on goods that are exempt, such as tools of trade and basic wearing apparel and bedding up to the prescribed value.'),
 ('Distress for Rent Act, Cap 293', 2,
  'Cap 293: a landlord may not break into locked premises to levy distress, and goods seized must be inventoried and may only be sold after the statutory period. Padlocking a tenant''s house or auctioning goods without a court process or certified bailiff exposes the landlord to a claim for illegal distress.'),
 ('Constitution of Kenya 2010 — housing, property and fair administrative action', 0,
  'Constitution of Kenya 2010, Article 43(1)(b): every person has the right to accessible and adequate housing, and to reasonable standards of sanitation.'),
 ('Constitution of Kenya 2010 — housing, property and fair administrative action', 1,
  'Constitution of Kenya 2010, Article 40: every person has the right to acquire and own property, and property shall not be arbitrarily deprived. A tenant''s goods are property protected by this article.'),
 ('Constitution of Kenya 2010 — housing, property and fair administrative action', 2,
  'Constitution of Kenya 2010, Article 47: every person has the right to administrative action that is expeditious, efficient, lawful, reasonable and procedurally fair, including written reasons where a right is adversely affected. Courts have relied on this and Article 43 to hold that evictions require adequate notice and due process.'),
 ('Constitution of Kenya 2010 — housing, property and fair administrative action', 3,
  'Constitution of Kenya 2010, Article 28 and Article 29: every person has inherent dignity and the right to security of the person. Locking a tenant out, cutting utilities, or using goons to evict violates these rights and is separately a criminal offence.')
) as c(title, idx, content) on c.title = d.title;

with t as (select id from public.legal_topics where name = 'employment'),
 d as (
  insert into public.documents (topic_id, title, source_name, source_url, content)
  select t.id, x.title, x.source_name, x.source_url, x.content from t, (values
    ('Employment Act 2007 — contracts, pay and termination',
     'Kenya Law, Employment Act No. 11 of 2007', 'https://www.kenyalaw.org',
     'Core statutory rights of employees in Kenya.'),
    ('Employment Act 2007 — leave, maternity and protection from discrimination',
     'Kenya Law, Employment Act No. 11 of 2007', 'https://www.kenyalaw.org',
     'Leave entitlements and anti-discrimination provisions.'),
    ('Work Injury Benefits Act 2007 and Occupational Safety and Health Act 2007',
     'Kenya Law, WIBA 2007 / OSHA 2007', 'https://www.kenyalaw.org',
     'Compensation and safety duties for workers.'),
    ('Labour Institutions Act 2007 and Labour Relations Act 2007',
     'Kenya Law, LIA 2007 / LRA 2007', 'https://www.kenyalaw.org',
     'Minimum wage machinery, unions and dispute resolution.')
  ) as x(title, source_name, source_url, content)
  returning id, title
)
insert into public.chunks (document_id, content, chunk_index)
select d.id, c.content, c.idx from d join (values
 ('Employment Act 2007 — contracts, pay and termination', 0,
  'Employment Act 2007, s.9: a contract of service for a period of three months or more, or which requires work that cannot reasonably be completed within three months, must be in writing. It is the employer''s duty to put it in writing; if there is a dispute, the burden of proving the terms lies on the employer.'),
 ('Employment Act 2007 — contracts, pay and termination', 1,
  'Employment Act 2007, s.10: the written contract must state the employee''s name, job description, date of commencement, form and duration of the contract, place of work, hours of work, remuneration and how it is calculated, and any leave, housing, sick pay or pension entitlements.'),
 ('Employment Act 2007 — contracts, pay and termination', 2,
  'Employment Act 2007, s.17-18: wages must be paid on the working day they fall due, in Kenyan currency, and may not be paid in alcohol or drugs. An employer may not impose unlawful deductions or conditions on where an employee spends their wages.'),
 ('Employment Act 2007 — contracts, pay and termination', 3,
  'Employment Act 2007, s.19: lawful deductions from wages are limited (tax, statutory contributions, agreed loan repayments, absence, damage caused by the employee''s wilful default, and similar). The total of all deductions may not exceed two-thirds of the wages due in any one month.'),
 ('Employment Act 2007 — contracts, pay and termination', 4,
  'Employment Act 2007, s.20: every employer must give a written itemised pay statement showing gross wages, all deductions and net pay, and must keep a record of it for at least twenty-four months.'),
 ('Employment Act 2007 — contracts, pay and termination', 5,
  'Employment Act 2007, s.35: notice of termination is at least one day for a daily-paid employee, at least one week where wages are paid weekly or fortnightly, and at least twenty-eight days where wages are paid monthly. Pay in lieu of notice may be given instead.'),
 ('Employment Act 2007 — contracts, pay and termination', 6,
  'Employment Act 2007, s.41: before terminating for misconduct, poor performance or physical incapacity, the employer must explain the reason in a language the employee understands, in the presence of a fellow employee or union representative, and must hear and consider the employee''s representations. Skipping this hearing makes the termination unfair.'),
 ('Employment Act 2007 — contracts, pay and termination', 7,
  'Employment Act 2007, s.43-45: the employer must prove the reason for termination; failure to do so makes it unfair. An employee may claim unfair termination, and s.49 allows the court to award up to twelve months'' gross wages as compensation, plus notice pay and reinstatement.'),
 ('Employment Act 2007 — contracts, pay and termination', 8,
  'Employment Act 2007, s.40: on redundancy the employer must give one month''s notice to the employee and the labour officer (and union if any), apply fair selection criteria, pay accrued leave in cash, one month''s pay in lieu of notice, and severance pay of at least fifteen days'' pay for each completed year of service.'),
 ('Employment Act 2007 — leave, maternity and protection from discrimination', 0,
  'Employment Act 2007, s.28: an employee is entitled to at least twenty-one working days of annual leave with full pay after twelve consecutive months of service, or a proportionate part where service is shorter.'),
 ('Employment Act 2007 — leave, maternity and protection from discrimination', 1,
  'Employment Act 2007, s.29: a female employee is entitled to three months'' maternity leave with full pay, and is not required to forfeit her annual leave. A male employee is entitled to two weeks'' paternity leave with full pay.'),
 ('Employment Act 2007 — leave, maternity and protection from discrimination', 2,
  'Employment Act 2007, s.30: after two consecutive months of service an employee is entitled to sick leave of not less than seven days with full pay and a further seven days with half pay in each period of twelve consecutive months, subject to a certificate from a registered medical practitioner.'),
 ('Employment Act 2007 — leave, maternity and protection from discrimination', 3,
  'Employment Act 2007, s.27: an employee is entitled to at least one rest day in every period of seven days, and working hours must be regulated by the contract or collective agreement.'),
 ('Employment Act 2007 — leave, maternity and protection from discrimination', 4,
  'Employment Act 2007, s.5: no employer shall discriminate against an employee or job applicant on grounds of race, colour, sex, language, religion, political opinion, nationality, ethnic or social origin, disability, pregnancy, marital status or HIV status. Equal pay for work of equal value is required.'),
 ('Employment Act 2007 — leave, maternity and protection from discrimination', 5,
  'Employment Act 2007, s.6: sexual harassment at work is prohibited, and an employer with twenty or more employees must issue a written sexual harassment policy.'),
 ('Employment Act 2007 — leave, maternity and protection from discrimination', 6,
  'Employment Act 2007, s.4: forced labour is prohibited; and s.56 prohibits employment of a child under thirteen, with restrictions on the work a child between thirteen and sixteen may do.'),
 ('Employment Act 2007 — leave, maternity and protection from discrimination', 7,
  'Employment Act 2007, s.90: a claim under the Act must generally be brought within three years after the act, omission or termination complained of.'),
 ('Work Injury Benefits Act 2007 and Occupational Safety and Health Act 2007', 0,
  'WIBA 2007, s.7: every employer must obtain and maintain an insurance policy covering their liability to pay compensation to employees for work-related injuries or disease. Failure to insure is an offence.'),
 ('Work Injury Benefits Act 2007 and Occupational Safety and Health Act 2007', 1,
  'WIBA 2007, s.10: an employee who is injured in an accident arising out of and in the course of employment is entitled to compensation, regardless of who was at fault. The employer may not require the employee to contribute to the cost of that cover (s.9).'),
 ('Work Injury Benefits Act 2007 and Occupational Safety and Health Act 2007', 2,
  'WIBA 2007, s.21-22: the accident must be reported to the Director of Occupational Safety and Health Services, and a claim should generally be made within twelve months of the accident or death.'),
 ('Work Injury Benefits Act 2007 and Occupational Safety and Health Act 2007', 3,
  'OSHA 2007, s.6: every occupier has a duty to ensure the safety, health and welfare of all persons working in the workplace, including safe plant and systems of work, training and supervision, and personal protective equipment at the employer''s cost (s.101).'),
 ('Labour Institutions Act 2007 and Labour Relations Act 2007', 0,
  'Labour Institutions Act 2007, s.43-46: the Wages Council machinery sets legally binding minimum wages by wage order. Paying below the applicable minimum wage order (including the general and agricultural wage orders) is unlawful regardless of what the contract says.'),
 ('Labour Institutions Act 2007 and Labour Relations Act 2007', 1,
  'Labour Relations Act 2007, s.4-7: every employee has the right to join a trade union and to participate in its lawful activities. It is unlawful for an employer to discriminate against, dismiss or threaten an employee for union membership or activity.'),
 ('Labour Institutions Act 2007 and Labour Relations Act 2007', 2,
  'Labour Relations Act 2007, s.76-81: a trade dispute may be reported to the Cabinet Secretary and referred to conciliation before industrial action. Protected strikes must follow the statutory notice and conciliation steps.'),
 ('Labour Institutions Act 2007 and Labour Relations Act 2007', 3,
  'Employment and Labour Relations Court Act 2011, s.12: the Employment and Labour Relations Court has exclusive jurisdiction over employment disputes, including unfair termination, unpaid wages and discrimination claims. A labour officer can assist with conciliation before filing.')
) as c(title, idx, content) on c.title = d.title;

with t as (select id from public.legal_topics where name = 'consumer'),
 d as (
  insert into public.documents (topic_id, title, source_name, source_url, content)
  select t.id, x.title, x.source_name, x.source_url, x.content from t, (values
    ('Consumer Protection Act 2012 — unfair practices and consumer agreements',
     'Kenya Law, Consumer Protection Act No. 46 of 2012', 'https://www.kenyalaw.org',
     'Rights against unfair practices, and remedies.'),
    ('Constitution of Kenya 2010 Article 46 and the Competition Act 2010',
     'Constitution of Kenya 2010 / Competition Act 2010', 'https://www.kenyalaw.org',
     'Constitutional consumer rights and false or misleading representations.'),
    ('Data Protection Act 2019 — personal data of consumers',
     'Kenya Law, Data Protection Act No. 24 of 2019', 'https://www.odpc.go.ke',
     'How businesses and lenders may use personal data.'),
    ('Small Claims Court Act 2016 — cheap and fast consumer remedies',
     'Kenya Law, Small Claims Court Act No. 2 of 2016', 'https://www.kenyalaw.org',
     'Where to take a small consumer or debt claim.')
  ) as x(title, source_name, source_url, content)
  returning id, title
)
insert into public.chunks (document_id, content, chunk_index)
select d.id, c.content, c.idx from d join (values
 ('Consumer Protection Act 2012 — unfair practices and consumer agreements', 0,
  'Consumer Protection Act 2012, s.12-13: it is an unfair practice to make a false, misleading or deceptive representation, including claiming goods have qualities or approvals they do not have, or advertising goods at a price the supplier does not intend to supply them at.'),
 ('Consumer Protection Act 2012 — unfair practices and consumer agreements', 1,
  'Consumer Protection Act 2012, s.14: an unconscionable representation, such as taking advantage of a consumer''s inability to understand the language or terms of an agreement, or a price grossly exceeding the value of similar goods, is an unfair practice.'),
 ('Consumer Protection Act 2012 — unfair practices and consumer agreements', 2,
  'Consumer Protection Act 2012, s.15-16: a consumer agreement entered into after an unfair practice may be rescinded by the consumer, and the consumer is entitled to a remedy including a refund; a notice of rescission may be given within one year.'),
 ('Consumer Protection Act 2012 — unfair practices and consumer agreements', 3,
  'Consumer Protection Act 2012, s.5 and s.88: any term in a consumer agreement that purports to require the consumer to waive rights given by the Act, or to submit compulsorily to arbitration in place of the Act''s remedies, is void.'),
 ('Consumer Protection Act 2012 — unfair practices and consumer agreements', 4,
  'Consumer Protection Act 2012, s.53-58 (credit agreements): a lender must disclose the total cost of credit, the annual percentage rate, all fees and charges, and the total amount payable in a written statement before the borrower signs. Undisclosed charges are not recoverable.'),
 ('Consumer Protection Act 2012 — unfair practices and consumer agreements', 5,
  'Consumer Protection Act 2012, s.65-67: goods supplied under a consumer agreement carry implied warranties of acceptable quality and fitness for purpose; a supplier may not contract out of them, and a consumer may claim repair, replacement or refund for defective goods.'),
 ('Consumer Protection Act 2012 — unfair practices and consumer agreements', 6,
  'Consumer Protection Act 2012, s.87: a consumer may bring proceedings in court for damages or rescission, and remedies under the Act are in addition to any other legal remedy available.'),
 ('Constitution of Kenya 2010 Article 46 and the Competition Act 2010', 0,
  'Constitution of Kenya 2010, Article 46: consumers have the right to goods and services of reasonable quality, to the information necessary to gain full benefit from them, to protection of their health, safety and economic interests, and to compensation for loss or injury from defective goods or services.'),
 ('Constitution of Kenya 2010 Article 46 and the Competition Act 2010', 1,
  'Competition Act 2010, s.55: false or misleading representations about goods or services, bait advertising, and unconscionable conduct in trade are prohibited. Complaints go to the Competition Authority of Kenya, which can order refunds and impose penalties.'),
 ('Constitution of Kenya 2010 Article 46 and the Competition Act 2010', 2,
  'Competition Act 2010, s.56-58: a supplier must not accept payment for goods or services it does not intend to supply, or supply goods that do not comply with a prescribed safety standard. Consumers may complain to the Competition Authority of Kenya free of charge.'),
 ('Data Protection Act 2019 — personal data of consumers', 0,
  'Data Protection Act 2019, s.25: personal data must be processed lawfully, fairly and transparently, collected for an explicit purpose, limited to what is necessary, kept accurate, and not retained longer than necessary.'),
 ('Data Protection Act 2019 — personal data of consumers', 1,
  'Data Protection Act 2019, s.26: a data subject has the right to be informed of the use of their data, to access it, to object to processing, to correction or deletion of false or misleading data, and to the deletion of data the controller no longer has a lawful reason to hold.'),
 ('Data Protection Act 2019 — personal data of consumers', 2,
  'Data Protection Act 2019, s.37: personal data may not be used for commercial purposes, including marketing, without the data subject''s consent or another lawful basis. Digital lenders contacting a borrower''s phone contacts to shame them breaches this and s.25.'),
 ('Data Protection Act 2019 — personal data of consumers', 3,
  'Data Protection Act 2019, s.56 and s.65: a data subject may lodge a complaint with the Office of the Data Protection Commissioner, which may issue enforcement notices and penalties, and may award compensation for damage suffered.'),
 ('Small Claims Court Act 2016 — cheap and fast consumer remedies', 0,
  'Small Claims Court Act 2016, s.12: the Small Claims Court hears claims for a liquidated sum of money not exceeding one million shillings, including contract disputes, refunds and similar money claims.'),
 ('Small Claims Court Act 2016 — cheap and fast consumer remedies', 1,
  'Small Claims Court Act 2016, s.15 and s.34: parties usually appear in person without an advocate, filing fees are low, and the court is required to determine a claim within sixty days of filing.'),
 ('Small Claims Court Act 2016 — cheap and fast consumer remedies', 2,
  'Small Claims Court Act 2016, s.38: a decision of the Small Claims Court may be appealed to the High Court only on a point of law, within thirty days, which keeps the process quick and final for most consumers.')
) as c(title, idx, content) on c.title = d.title;